### ISSUE TITLE
python 3 migration and other enhancements

### ISSUE THREAD

**Issue by nouse4anick** [scotthibbs/FDLog_Enhanced#12]
so, we need to work on getting the program updated to python 3. however I think that we should work on a few other things and have a few things in the back of our head:

- python 2.7 while deprecated should still work after 2020, they just won't have any more features or bug fixes added
- the biggest change is going to be the print function, however we don't use it much in the program (510 matches using 'print' as the search term), it will be easy enough to find those and throw ()'s around it.
- we should look at the original code and include some of the updates (namely the gui startup interface), this will help simplify code and hopefully shorten it (those if statements suck!)

after that is done and implemented we should then port and test python 3 compatibility, we should have the program done by december if at all possible.

**Comment by stillline** [comment]
I found your software while googling for python based field day software. I've tried running it on my raspberry pi (buster) using python3 and i get some "print' errors. I threw some () around one and it went away but there's various other exceptions as well. 

Wondering if theres a way for me to run this in 2.7, I'm pretty new to python in general. Sorry if this comment doesn't belong here. 

I hope to use this software at our field day operation this year. 

Regards. 
Matthew Simmons - KM6TOA

**Comment by scotthibbs** [comment]
It has not been ported to python 3. It is written in 2.7.

I am no longer using it for fd as I moved away from my old club. :(

You are free to port it to python 3 and make more enhancements.

Good luck.

Scott

**Comment by B1QUAD** [comment]
I have started a python 3 port, the gui works and I'm able to enter logs. The only bug I've been able to find has to do with my changes to the netsync.ckauth function, but since I'm not able to test the networking functionality as of now I can't be certain what other bugs might be left in the ported version.

Any help with porting the code would be super helpful.
Here is the link to my fork: [https://github.com/B1QUAD/FDLog_Enhanced_python3](https://github.com/B1QUAD/FDLog_Enhanced_python3)
Edit: I forgot to add the destination URL.

**Comment by scotthibbs** [comment]
David B1QUAD was kind enough to send me a copy of his python 3 work. I hope to get this working soon so we can port over. 

I'm thinking some testing on the latest 2.7 python version so it can be released as a stable, then work on python 3.

**Comment by scotthibbs** [comment]
Now done.
