### ISSUE TITLE
ip address modification

### ISSUE THREAD

**Issue by nouse4anick** [scotthibbs/FDLog_Enhanced#2]
in the netsync class you can get rid of lines 1350  to 1379 (ish) and replace with this:
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
try:
	s.connect(("8.8.8.8", 53))
	my_addr= s.getsockname()[0]
except:
	my_addr= '127.0.0.1'
finally:
	s.close()
bc_addr = re.sub(r'[0-9]+$', '255', my_addr)  # calc bcast addr

The main reason for this edit is to remove all the checks for 'different ip setups' (ie, 10.x.x.x and 172.x.x.x etc) and to make it cross-platform compatible, this gives you a one-shot method of getting the ip address.

still working on getting the netmask to work, however, I am not finding anywhere it's actually used... i've searched the entire file and its not used in any function, maybe we can get rid of it?

**Comment by scotthibbs** [comment]
I didn't know there were issues with the netsync class that I had fixed.  All platforms and networks work well as far as I know.

The code above is already in the program. (the s.connect address doesn't have to be reachable so it could be any address). I think we can get rid of the netmask because someone already did that in 2011. See https://groups.google.com/forum/#!topic/fdlog/COGEpTNLwUg and his changes on mercurial. In that code, he changes the broadcast ip to 255.255.255.255.  I'm not much of a network guy, but would that work on a 172 network as well? The check for the different router network scheme like 172 is just to set the netmask, so once removed, no need to check.

I use github desktop. There are videos online on how to use it (or I would be lost). I started saving my changes to github as I go now (because I code at home and work (when bored). 

I look forward to improving the program with you!

**Comment by nouse4anick** [comment]
it was cross-platform compatible, however, there was some unnecessary code left in (which I commented out and will remove when I get a chance) that might cause some failure on other networks. 

I do have github desktop too, I also use linux and can test both versions on my network from separate computers.
